// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// linearCluster
List linearCluster(NumericVector x, double tolerance, Nullable<NumericVector> weight);
RcppExport SEXP _VisualBasic_R_linearCluster(SEXP xSEXP, SEXP toleranceSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(linearCluster(x, tolerance, weight));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VisualBasic_R_linearCluster", (DL_FUNC) &_VisualBasic_R_linearCluster, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_VisualBasic_R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
